# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'db/schema.rb'

Style/Encoding:
  Enabled: true

Documentation:
  Enabled: false